### ISSUE TITLE
Data row editor save button behaves oddly in create mode

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-frontend#207]
### How to Reproduce
* Open editor for new instance of TypeTest
* Scroll to the bottom, check the save button
* Fill in the ID field with a unique value
* Scroll to the bottom, check the save button

### Expected behavior
The standard HTML form and old form behavior:
* Save button never gets disabled
* Once you've pressed it, invalid fields are marked in red

### Observed behavior
The save button is disabled
An error message is shown beside the save button
Only fields you've touched are marked, so it's hard to spot which fields are blocking submission

**Comment by connoratrug** [comment]
@fdlk If the form is long ( 5, 10, 30+ fields) it's not very nice when i fill in the form, try to submit, get told some field is incorrect, find the field, update the field. scroll to submit, get told its still incorrect, scroll back to the field, update the field again, get told some other field is incorrect, ... etc.. 

I would ague if the (large) form knows that the data in the form-field can not be submitted as is, the user should be made aware of this. ( or if the forms knows/thinks the data is valid, the user should be made aware of this)

**Comment by fdlk** [comment]
@connoratrug I'd expect normal browser behavior, e.g. https://getbootstrap.com/docs/4.5/components/forms/#browser-defaults

So you can tab through the fields to the submit button if you like, no red messages yet, but once a field is dirty, or once you click submit, you get feedback until it's fixed.
