### ISSUE TITLE
Data row editor eats up server error message

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-frontend#209]
### How to Reproduce
Open type test in data row editor
Set string attribute to a value with more than 255 characters
Press save
The save fails and an error is shown

### Expected behavior
The server's error message is shown to the user

### Observed behavior
The server's error message is hidden from the user and the alert says
> An error has occurred

**Comment by jvanveen** [comment]
Volgens mij is deze al gefixed. Input velden hebben een maxlength attribute van 255 characters, waardoor dit niet meer mogelijk is.

**Comment by fdlk** [comment]
@jvanveen There's other ways to trigger this, and always will be. E.g. when server goes down and you post a valid form.

**Comment by jelmerveen** [comment]
It's still a bug: When a required field is empty, it says 'error occured'
Maybe check the forms repository
