### ISSUE TITLE
Changing entity in url in Data Explorer 2 doesn't trigger routing

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-frontend#286]
### How to Reproduce
Go to master.dev.molgenis.org
click on experimental and click on Collections
Change the eu_bbmri_eric_collections to eu_bbmri_eric_biobanks

### Expected behavior
View is updated to represent new selected entity

### Observed behavior
No change in the frontend

**Comment by connoratrug** [comment]
work around is to hit 'enter' key
