### ISSUE TITLE
$.cookie is not a function

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-frontend#294]
### How to Reproduce
- Go to https://master.dev.molgenis.org/
- Open developer console

### Expected behavior
No errors

### Observed behavior
`home:29 Uncaught TypeError: $.cookie is not a function`

`$.cookie('permissionforcookies'))` is used in some GA tracking script.

**Comment by jelmerveen** [comment]
This is also broken for biobank explorer, it is inside molgenis.

**Comment by jelmerveen** [comment]
placed issue on molgenis repo
