### ISSUE TITLE
Changing Security permission fails with unknown entity exception

### ISSUE THREAD

**Issue by jvanveen** [molgenis/molgenis-frontend#336]
### How to Reproduce
* Log in
* Got to http://localhost:8081/group/catalogue-import for example
* Change the permission with one of the radio button

### Expected behavior
The permission is updated without errors, the Save button is enabled again.

### Observed behavior
Due to the thrown exception, the Save button is kept disabled. No message occurs.
![Screenshot_20200810_133246](https://user-images.githubusercontent.com/48799939/89779282-419caa00-db0f-11ea-878b-66f4a70c5522.png)

**Comment by MaxPostema** [comment]
fixed here: https://github.com/molgenis/molgenis-frontend/pull/338
