### ISSUE TITLE
No analytics footer message when setting Google analytics tracking ID (MOLGENIS)

### ISSUE THREAD

**Issue by jvanveen** [molgenis/molgenis-frontend#491]
### How to Reproduce
* Goto /menu/admin/settings/sys_set_app
* Fill in "test" for 'Google analytics tracking ID (MOLGENIS)'

### Expected behavior
An analytics message should appear in the footer

### Observed behavior
No analytics message appears

**Comment by connoratrug** [comment]
The warning now appears as a popover instead of in the footer, when you accept the cookie is set preventing the warning from being shown a second time
