### ISSUE TITLE
Missing language selection pulldown

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-frontend#492]
### How to Reproduce
Enable multiple Language's in sys_Language

### Expected behavior
A Language selection in the menu bar

### Observed behavior
No way to select language
(NOTE: the html is there and renders a small box, guessing its a styling issue )

**Comment by jvanveen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#7759 Missing language select](https://trello.com/c/2qYRn5gN/376-7759-missing-language-select)

**Comment by MaxPostema** [comment]
https://github.com/molgenis/molgenis-theme/issues/46
fixed here
