### ISSUE TITLE
Missing Groups header when logged in as group manager

### ISSUE THREAD

**Issue by fdlk** [molgenis/molgenis-frontend#493]
### How to Reproduce
Log in as a user who has role manager on one group
Open the Security UI
Check the Groups table

### Expected behavior
There is a "Groups" header over it, just like when you're logged in as superuser
![Schermafbeelding 2021-01-14 om 13 07 38](https://user-images.githubusercontent.com/1523838/104589342-011afc80-566a-11eb-8077-5bcb3b6456ae.png)

### Observed behavior
The "Groups" header is missing(!)
![Schermafbeelding 2021-01-14 om 13 12 18](https://user-images.githubusercontent.com/1523838/104589450-2c055080-566a-11eb-877c-cee312c23628.png)

**Comment by jvanveen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#7759 Missing Groups header](https://trello.com/c/oxEzCag6/373-7759-missing-groups-header)
