### ISSUE TITLE
Safari Select tag rendering error in data-explorer's table view

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-frontend#541]
### How to Reproduce
Go to data-explorer tableview using safari.

### Expected behavior
The "order by" select element respects bootstraps styling.

### Observed behavior
The "order by" select element has 2 sets of arrows and broken styling

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [broken safari rendering: https://github.com/molgenis/molgenis-frontend/issues/541](https://trello.com/c/6U0pMIAR/420-broken-safari-rendering-https-githubcom-molgenis-molgenis-frontend-issues-541)

**Comment by connoratrug** [comment]
This seems like a issue in https://github.com/molgenis/molgenis-theme , if you change the theme to the default bootstrap 4 style the select renders correctly 
![Screenshot 2021-02-22 at 16 51 06](https://user-images.githubusercontent.com/47183404/108732840-369aeb80-752e-11eb-98c7-452d30538b6a.png)

**Comment by connoratrug** [comment]
created issue in theme repo: https://github.com/molgenis/molgenis-theme/issues/74

**Comment by connoratrug** [comment]
resolved by theme update
