### ISSUE TITLE
Cant reach download dialog if there are items in the shopping cart

### ISSUE THREAD

**Issue by MaxPostema** [molgenis/molgenis-frontend#560]
### How to Reproduce
- Have items in shoppingcart
- Download data via new dataexplorer 

### Expected behavior
Have 2 information fields in lower corner

### Observed behavior
The 2 fields are on top of each other en your download is unreachable.

<img width="396" alt="Schermafbeelding 2021-03-08 om 16 42 29" src="https://user-images.githubusercontent.com/46395349/110344154-81882900-802d-11eb-9dfe-75842e626c22.png">

### Bonus points

Have the dialogs use the same style

**Comment by connoratrug** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data explorer overlapping toasts ( z-index issue)](https://trello.com/c/O90nfoGU/455-data-explorer-overlapping-toasts-z-index-issue)

**Comment by MaxPostema** [comment]
closed by https://github.com/molgenis/molgenis-frontend/pull/581
