### ISSUE TITLE
Metadata Manager does not show rangeMin & rangeMax values

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-frontend#609]
### How to Reproduce
1. Import a file with ranges ([genturis_v2.xlsx](https://github.com/molgenis/molgenis-frontend/files/6421010/genturis_v2.xlsx))
2. Go to the Metadata Manager
3. Open `Subject`
4. Look at attribute `What was the age (years) of the patient at last colonoscopy?` under `Patient information`

### Expected behavior
The `Minimum range` has value 0, the `Maximum range` has value 500.

### Observed behavior
Both fields are empty.

**Comment by jelmerveen** [comment]
fixed in  #611
