### ISSUE TITLE
Data-row-edit plugin shows an error for fields with a 'new' expression 

### ISSUE THREAD

**Issue by dtroelofsprins** [molgenis/molgenis-frontend#711]
It appears that when adding a new row to a table using the data-row-edit plugin. Fields having an expression might show a strange error. In fact it's a warning because you are able to save data. And when an invalid value is entered the 'validation failed' error occurs. 
![image](https://user-images.githubusercontent.com/57137088/140480798-6e717000-e549-495d-acef-5151f35f6ca4.png)

It turns out that now all fields with an expression show this error. The country_code also has a validation expression, however no error is shown.
The expressions for the iso2_code and iso3_code are: 
regex('^[a-z]{2}$', {iso2_code}, 'i')
regex('^[a-z]{3}$', {iso3_code}, 'I')

and for the country_code:
regex('^[0-9]{3}$', {country_code})

After some trial and error is turns out that when I remove the 'i' from the first two expressions no warning is shown.

[test_expr.xlsx](https://github.com/molgenis/molgenis-frontend/files/7481709/test_expr.xlsx)

**Comment by fdlk** [comment]
This is a bug in the expression library, where a case is missing for a given regex, a null value and flags

**Comment by tommydeboer** [comment]
Fixed in https://github.com/molgenis/molgenis-expressions/pull/13
